# Started recording 2015-07-29 09:26:47 UTC
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (2, '_edit_lock', '1438162023:1') ;
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (2, '_edit_last', '1') ;
UPDATE `wp_posts` SET `post_author` = 1, `post_date` = '2014-04-02 03:28:49', `post_date_gmt` = '2014-04-02 03:28:49', `post_content` = 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin\' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href=\"http://localhost:8888/wordpress/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!\r\n\r\na test from Duy', `post_content_filtered` = '', `post_title` = 'Sample Page', `post_excerpt` = '', `post_status` = 'publish', `post_type` = 'page', `comment_status` = 'open', `ping_status` = 'open', `post_password` = '', `post_name` = 'sample-page', `to_ping` = '', `pinged` = '', `post_modified` = '2015-07-29 09:27:18', `post_modified_gmt` = '2015-07-29 09:27:18', `post_parent` = 0, `menu_order` = 0, `post_mime_type` = '', `guid` = 'http://localhost:8888/wordpress/?page_id=2' WHERE `ID` = 2 ;
INSERT INTO `wp_posts` (`post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_content_filtered`, `post_title`, `post_excerpt`, `post_status`, `post_type`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_parent`, `menu_order`, `post_mime_type`, `guid`) VALUES (1, '2015-07-29 09:27:18', '2015-07-29 09:27:18', 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I\'m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin\' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href=\"http://localhost:8888/wordpress/wp-admin/\">your dashboard</a> to delete this page and create new pages for your content. Have fun!\r\n\r\na test from Duy', '', 'Sample Page', '', 'inherit', 'revision', 'open', 'open', '', '2-revision-v1', '', '', '2015-07-29 09:27:18', '2015-07-29 09:27:18', 2, 0, '', '') ;
UPDATE `wp_posts` SET `guid` = 'http://localhost:8888/wordpress/?p=8' WHERE `ID` = 8 ;
UPDATE `wp_postmeta` SET `meta_value` = '1438162038:1' WHERE `post_id` = 2 AND `meta_key` = '_edit_lock' ;
UPDATE `wp_postmeta` SET `meta_value` = '1438162039:1' WHERE `post_id` = 2 AND `meta_key` = '_edit_lock' ;
UPDATE `wp_postmeta` SET `meta_value` = '1438162107:1' WHERE `post_id` = 2 AND `meta_key` = '_edit_lock' AND `meta_value` = '1438162039:1' ;
INSERT IGNORE INTO `wp_options` ( `option_name`, `option_value`, `autoload` ) VALUES ('auto_updater.lock', '1438313731', 'no') /* LOCK */ ;
UPDATE `wp_options` SET `option_value` = '1438313731' WHERE `option_name` = 'auto_updater.lock' ;
DELETE FROM `wp_options` WHERE `option_name` = 'auto_updater.lock' ;
INSERT IGNORE INTO `wp_options` ( `option_name`, `option_value`, `autoload` ) VALUES ('auto_updater.lock', '1438313739', 'no') /* LOCK */ ;
UPDATE `wp_options` SET `option_value` = '1438313740' WHERE `option_name` = 'auto_updater.lock' ;
DELETE FROM `wp_options` WHERE `option_name` = 'auto_updater.lock' ;
UPDATE `wp_options` SET `option_value` = '' WHERE `option_name` = 'db_upgraded' ;
INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('can_compress_scripts', '1', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) ;
# a test line
# a new test line
